# Generated by Django 4.2.16 on 2026-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_co_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_way',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='max_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='rsrv_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='rsrv_type_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_co_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_way',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='max_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
