# Generated by Django 4.2.16 on 2026-09-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_products', '0002_alter_depositproduct_dcls_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=10)),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200)),
                ('loan_inci_expn', models.TextField(blank=True)),
                ('erly_rpay_fee', models.TextField(blank=True)),
                ('dly_rate', models.TextField(blank=True)),
                ('loan_lmt', models.TextField(blank=True)),
                ('interest_user', models.ManyToManyField(blank=True, related_name='interest_mortgage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MortgageLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrtg_type_nm', models.CharField(max_length=100)),
                ('rpay_type_nm', models.CharField(max_length=100)),
                ('lend_rate_type_nm', models.CharField(max_length=100)),
                ('lend_rate_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lend_rate_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lend_rate_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financial_products.mortgageloanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='JeonseLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=10)),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200)),
                ('loan_inci_expn', models.TextField(blank=True)),
                ('erly_rpay_fee', models.TextField(blank=True)),
                ('dly_rate', models.TextField(blank=True)),
                ('loan_lmt', models.TextField(blank=True)),
                ('interest_user', models.ManyToManyField(blank=True, related_name='interest_jeonse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JeonseLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpay_type_nm', models.CharField(max_length=100)),
                ('lend_rate_type_nm', models.CharField(max_length=100)),
                ('lend_rate_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lend_rate_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lend_rate_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financial_products.jeonseloanproduct')),
            ],
        ),
    ]
