# Generated by Django 4.2.16 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_banks',
            field=models.JSONField(blank=True, default=list, verbose_name='관심 지점 목록'),
        ),
    ]
