# Generated by Django 4.2.16 on 2025-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SilverPrice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('buy_price_per_don', models.IntegerField(blank=True, help_text='내가 살때 가격 (원/3.75g)', null=True)),
                ('sell_price_per_don', models.IntegerField(blank=True, help_text='내가 팔때 가격 (원/3.75g)', null=True)),
                ('buy_price_per_gram', models.IntegerField(blank=True, help_text='내가 살때 가격 (원/g)', null=True)),
                ('sell_price_per_gram', models.IntegerField(blank=True, help_text='내가 팔때 가격 (원/g)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '은 시세',
                'verbose_name_plural': '은 시세 목록',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(choices=[('04020000', '금 99.99_1Kg'), ('04030000', '은 99.99_1Kg')], max_length=20)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='종가', max_digits=12)),
                ('change_value', models.DecimalField(decimal_places=2, help_text='전일대비 등락값', max_digits=12, null=True)),
                ('change_rate', models.DecimalField(decimal_places=2, help_text='전일대비 등락률(%)', max_digits=5, null=True)),
                ('open_price', models.DecimalField(decimal_places=2, help_text='시가', max_digits=12, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='고가', max_digits=12, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='저가', max_digits=12, null=True)),
                ('trade_volume', models.DecimalField(decimal_places=2, help_text='거래량', max_digits=20, null=True)),
            ],
            options={
                'ordering': ['prod_code', 'date'],
                'unique_together': {('prod_code', 'date')},
            },
        ),
    ]
